name: campus_event_finder
description: "Campus Event Finder – discover, save, and register for university events."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.12.1

dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.0
  provider: ^6.1.2
  shared_preferences: ^2.2.3
  cached_network_image: ^3.3.1
  url_launcher: ^6.2.6
  google_fonts: ^6.2.1
  sqflite: ^2.3.3
  path: ^1.9.0
  sqflite_common_ffi: ^2.3.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  flutter_launcher_icons: ^0.14.3

flutter_launcher_icons:
  android: true
  ios: true
  image_path: assets/app_icon.png
  min_sdk_android: 21
  remove_alpha_ios: true
  adaptive_icon_background: "#0B0B14"
  adaptive_icon_foreground: assets/app_icon.png
  web:
    generate: true
    image_path: assets/app_icon.png
    background_color: "#0B0B14"
    theme_color: "#7C6CF0"
  windows:
    generate: true
    image_path: assets/app_icon.png
    icon_size: 256
  macos:
    generate: true
    image_path: assets/app_icon.png

flutter:
  uses-material-design: true
